version: "3.4"
services:
    cassandra:
        container_name: cassandra
        image: cassandra:3.11.8
        ports:
            - 7000:7000 # cluster communication
            - 7001:7001 # cluster communication (SSL)
            - 9042:9042 # cql
        environment:
            - CASSANDRA_BROADCAST_ADDRESS=172.16.239.12
            - TZ=Etc/GMT # use UTC
        volumes:
            - ${PWD}/dev:/etc/cassandra
        networks:
            app_net:
                ipv4_address: 172.16.239.12

    tests:
        # this container has cqlsh installed and it also has the Go tests.
        # bash into the container to run the tests manually
        image: test-cassandra
        restart: always
        entrypoint: ["cqlsh", "cassandra.test-cassandra_app_net", "9042", "cassandra", "-u", "cassandra", "-p", "cassandra"]
        depends_on:
            - cassandra
        networks:
            app_net:
                ipv4_address: 172.16.239.13

networks:
  app_net:
    ipam:
      driver: default
      config:
        - subnet: "172.16.239.0/24"
        - subnet: "2001:3984:3989::/64"
